server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never

spring:
  web:
    resources:
      add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password

logging:
  file:
    path: /
    name: springLog.log
  pattern:
    console: "%d [%level] %c{1.} [%t] %m%n"
    file: "%d [%level] %c{1.} [%t] %m%n"

management:
  endpoints:
    web:
      exposure:
        include: "metrics,prometheus"



