FORMAT: 1A
HOST: http://localhost:8080/api

# ActiveEdge Interview


# Group Misc

## Stocks [/stocks]

### Get Stocks [GET]

+ Response 200 (application/json;charset=UTF-8)

        OK


    + Headers

            Vary:Origin
            X-Content-Type-Options:nosniff
            X-XSS-Protection:1; mode=block
            Cache-Control:no-cache, no-store, max-age=0, must-revalidate
            Pragma:no-cache
            Expires:0
            X-Frame-Options:DENY
            Content-Length:152
            Date:Sat, 27 Nov 2021 12:37:47 GMT
            Keep-Alive:timeout=60
            Connection:keep-alive

    + Attributes (Get Stocks)


    + Body

            {
              "path": "/api/stocks/",
              "timestamp": "2021-11-27 13:37:47",
              "response_state": true,
              "status": 200,
              "data": [
                {
                  "name": "Stock",
                  "amount": {
                    "currentPrice": "30.00"
                  }
                }
              ]
            }


### Create Stock [POST]

+ Request (application/json)

    + Attributes (Create Stock Request)


    + Body

            {
                "name": "Stock",
                "amount": {
                    "currentPrice": 30.0
                }
            }


+ Response 400 (application/json;charset=UTF-8)

        Bad Request


    + Headers

            Vary:Origin
            X-Content-Type-Options:nosniff
            X-XSS-Protection:1; mode=block
            Cache-Control:no-cache, no-store, max-age=0, must-revalidate
            Pragma:no-cache
            Expires:0
            X-Frame-Options:DENY
            Content-Length:190
            Date:Sat, 27 Nov 2021 12:33:20 GMT
            Connection:close

    + Attributes (Validation Err1)


    + Body

            {
              "path": "/api/stocks",
              "timestamp": "2021-11-27 13:33:20",
              "response_state": false,
              "status": 400,
              "data": {
                "message": "Validation failed",
                "error": "Bad Request",
                "errors": {
                  "name": "Enter stock name"
                }
              }
            }


+ Response 201 (application/json;charset=UTF-8)

        Created


    + Headers

            Vary:Origin
            X-Content-Type-Options:nosniff
            X-XSS-Protection:1; mode=block
            Cache-Control:no-cache, no-store, max-age=0, must-revalidate
            Pragma:no-cache
            Expires:0
            X-Frame-Options:DENY
            Content-Length:108
            Date:Sat, 27 Nov 2021 12:33:59 GMT
            Keep-Alive:timeout=60
            Connection:keep-alive

    + Attributes (Create Stock)


    + Body

            {
              "path": "/api/stocks",
              "timestamp": "2021-11-27 13:33:59",
              "response_state": true,
              "status": 201,
              "data": "Created"
            }



### Get Stock [GET /{stockId}]

+ Parameters
    + stockId (number, required)

        + Sample: 1

+ Response 404 (application/json;charset=UTF-8)

        Not Found


    + Headers

            Vary:Origin
            X-Content-Type-Options:nosniff
            X-XSS-Protection:1; mode=block
            Cache-Control:no-cache, no-store, max-age=0, must-revalidate
            Pragma:no-cache
            Expires:0
            X-Frame-Options:DENY
            Content-Length:151
            Date:Sat, 27 Nov 2021 11:43:20 GMT
            Keep-Alive:timeout=60
            Connection:keep-alive

    + Attributes (Stock Not Found Err1)


    + Body

            {
              "path": "/api/stocks/1",
              "timestamp": "2021-11-27 12:43:20",
              "response_state": false,
              "status": 404,
              "data": {
                "message": "Stock not found",
                "error": "Not Found"
              }
            }


+ Response 200 (application/json;charset=UTF-8)

        OK


    + Headers

            Vary:Origin
            X-Content-Type-Options:nosniff
            X-XSS-Protection:1; mode=block
            Cache-Control:no-cache, no-store, max-age=0, must-revalidate
            Pragma:no-cache
            Expires:0
            X-Frame-Options:DENY
            Content-Length:204
            Date:Sat, 27 Nov 2021 12:36:20 GMT
            Keep-Alive:timeout=60
            Connection:keep-alive

    + Attributes (Get Stock)


    + Body

            {
              "path": "/api/stocks/1",
              "timestamp": "2021-11-27 13:36:20",
              "response_state": true,
              "status": 200,
              "data": {
                "name": "Stock",
                "amount": {
                  "currentPrice": "30.00"
                },
                "stockId": 1,
                "creationDate": "2021-11-27T01:33:59.181"
              }
            }


### Update Stock [PUT /{stockId}]

+ Parameters
    + stockId (number, required)

        + Sample: 1

+ Request (application/json)

    + Attributes (Update Stock Request)


    + Body

            {
                "name": "Stock",
                "amount": {
                    "currentPrice": 30.0
                }
            }


+ Response 200 (application/json;charset=UTF-8)

        OK


    + Headers

            Vary:Origin
            X-Content-Type-Options:nosniff
            X-XSS-Protection:1; mode=block
            Cache-Control:no-cache, no-store, max-age=0, must-revalidate
            Pragma:no-cache
            Expires:0
            X-Frame-Options:DENY
            Content-Length:110
            Date:Sat, 27 Nov 2021 12:36:48 GMT
            Keep-Alive:timeout=60
            Connection:keep-alive

    + Attributes (Update Stock)


    + Body

            {
              "path": "/api/stocks/1",
              "timestamp": "2021-11-27 13:36:48",
              "response_state": true,
              "status": 200,
              "data": "Updated"
            }


+ Response 404 (application/json;charset=UTF-8)

        Not Found


    + Headers

            Vary:Origin
            X-Content-Type-Options:nosniff
            X-XSS-Protection:1; mode=block
            Cache-Control:no-cache, no-store, max-age=0, must-revalidate
            Pragma:no-cache
            Expires:0
            X-Frame-Options:DENY
            Content-Length:151
            Date:Sat, 27 Nov 2021 12:37:25 GMT
            Keep-Alive:timeout=60
            Connection:keep-alive

    + Attributes (Stock Not Found Err1)


    + Body

            {
              "path": "/api/stocks/2",
              "timestamp": "2021-11-27 13:37:25",
              "response_state": false,
              "status": 404,
              "data": {
                "message": "Stock not found",
                "error": "Not Found"
              }
            }


### Delete Stock [DELETE/{stockId}]

+ Parameters
    + stockId (number, required)

        + Sample: 1

+ Response 200 (application/json;charset=UTF-8)

        OK


    + Headers

            Vary:Origin
            X-Content-Type-Options:nosniff
            X-XSS-Protection:1; mode=block
            Cache-Control:no-cache, no-store, max-age=0, must-revalidate
            Pragma:no-cache
            Expires:0
            X-Frame-Options:DENY
            Content-Length:110
            Date:Sat, 27 Nov 2021 12:38:11 GMT
            Keep-Alive:timeout=60
            Connection:keep-alive

    + Attributes (Delete Stock)


    + Body

            {
              "path": "/api/stocks/1",
              "timestamp": "2021-11-27 13:38:11",
              "response_state": true,
              "status": 200,
              "data": "Deleted"
            }


+ Response 404 (application/json;charset=UTF-8)

        Not Found


    + Headers

            Vary:Origin
            X-Content-Type-Options:nosniff
            X-XSS-Protection:1; mode=block
            Cache-Control:no-cache, no-store, max-age=0, must-revalidate
            Pragma:no-cache
            Expires:0
            X-Frame-Options:DENY
            Content-Length:151
            Date:Sat, 27 Nov 2021 12:38:35 GMT
            Keep-Alive:timeout=60
            Connection:keep-alive

    + Attributes (Stock Not Found Err1)


    + Body

            {
              "path": "/api/stocks/1",
              "timestamp": "2021-11-27 13:38:35",
              "response_state": false,
              "status": 404,
              "data": {
                "message": "Stock not found",
                "error": "Not Found"
              }
            }




# Data Structures

## Get Stocks (object)


### Properties
+ `path` (string, required) 
+ `timestamp` (string, required) 
+ `response_state` (boolean, required) 
+ `status` (number, required) 
+ `data` (array[Datum], required) 


## Datum (object)


### Properties
+ `name` (string, required) 
+ `amount` (Amount, required) 


## Amount (object)


### Properties
+ `currentPrice` (string, required) 


## Data (object)


### Properties
+ `message` (string, required) 
+ `error` (string, required) 


## Stock Not Found Err1 (object)


### Properties
+ `path` (string, required) 
+ `timestamp` (string, required) 
+ `response_state` (boolean, required) 
+ `status` (number, required) 
+ `data` (Data, required) 


## Get Stock (object)


### Properties
+ `path` (string, required) 
+ `timestamp` (string, required) 
+ `response_state` (boolean, required) 
+ `status` (number, required) 
+ `data` (Data2, required) 


## Data2 (object)


### Properties
+ `name` (string, required) 
+ `amount` (Amount, required) 
+ `stockId` (number, required) 
+ `creationDate` (string, required) 


## Create Stock Request (object)


### Properties
+ `name` (string, required) 
+ `amount` (Amount2, required) 


## Amount2 (object)


### Properties
+ `currentPrice` (number, required) 


## Data3 (object)


### Properties
+ `message` (string, required) 
+ `error` (string, required) 
+ `errors` (Errors, required) 


## Errors (object)


### Properties
+ `name` (string, required) 


## Validation Err1 (object)


### Properties
+ `path` (string, required) 
+ `timestamp` (string, required) 
+ `response_state` (boolean, required) 
+ `status` (number, required) 
+ `data` (Data3, required) 


## Create Stock (object)


### Properties
+ `path` (string, required) 
+ `timestamp` (string, required) 
+ `response_state` (boolean, required) 
+ `status` (number, required) 
+ `data` (string, required) 


## Update Stock Request (object)


### Properties
+ `name` (string, required) 
+ `amount` (Amount2, required) 


## Update Stock (object)


### Properties
+ `path` (string, required) 
+ `timestamp` (string, required) 
+ `response_state` (boolean, required) 
+ `status` (number, required) 
+ `data` (string, required) 


## Delete Stock (object)


### Properties
+ `path` (string, required) 
+ `timestamp` (string, required) 
+ `response_state` (boolean, required) 
+ `status` (number, required) 
+ `data` (string, required) 

